apiVersion: v2
name: kepler
description: A Helm chart for kepler
type: application
version: 0.3.4
appVersion: latest
home: https://sustainable-computing.io/html/index.html
sources:
  - https://github.com/sustainable-computing-io/kepler
